# Generated by Django 3.2.6 on 2021-10-27 02:35

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211025_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=api.fields.LowerCaseCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=api.fields.LowerCaseCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=api.fields.LowerCaseCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=api.fields.LowerCaseCharField(max_length=255),
        ),
    ]
