# Generated by Django 3.2.6 on 2021-10-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211027_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='trending',
            new_name='bestseller',
        ),
    ]
