import Head from "next/head";
import Attract from "../components/Content/Attract";
import ContentContainer from "../components/Content/Container";
import Gap from "../components/Gap";
import Footer from "../components/Layout/Footer";
import Header from "../components/Layout/Header";
import Subheader from "../components/Layout/Subheader";
import Wrapper from "../components/Layout/Wrapper";
// import BestSellers from "../components/Content/BestSellers";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cupsholic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Subheader />
        <Header />
        <ContentContainer>
          <Attract />
          <Gap height="50px" />
          {/* <BestSellers /> */}
        </ContentContainer>
        <Footer />
      </Wrapper>
    </>
  );
}
