import Head from "next/head";
import Attract from "../components/Content/Attract";
import BestSellers from "../components/Content/BestSellers";
import ContentContainer from "../components/Content/Container";
import LimitSale from "../components/Content/LimitSales";
import NewArrivals from "../components/Content/NewArrivals";
import Gap from "../components/Gap";
import Footer from "../components/Layout/Footer";
import Header from "../components/Layout/Header";
import Subheader from "../components/Layout/Subheader";
import Wrapper from "../components/Layout/Wrapper";
// import NewBlog from "../components/Content/NewBlog";
import ScrollToTop from "../components/ScrollToTop";
import OverlayContainer from "../components/Layout/OverlayContainer";
import { useState } from "react";

export default function Home() {
  const [isOpenMenu, setIsOpenMenu] = useState(false);
  function handleOpenMenu() {
    setIsOpenMenu(true);
  }
  function handleCloseMenu() {
    setIsOpenMenu(false);
    console.log("closeee");
  }
  return (
    <>
      <Head>
        <title>Cupsholic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <Subheader />
        <Header onOpenMenu={handleOpenMenu} />
        <ContentContainer>
          <Attract />
          <Gap height="50px" />
          <BestSellers />
          <Gap height="50px" />
          <LimitSale />
          <Gap height="45px" />
          <NewArrivals />
          {/* <NewBlog /> */}
        </ContentContainer>
        <Footer />
        <ScrollToTop />
        <OverlayContainer isOpenMenu={isOpenMenu} onClose={handleCloseMenu} />
      </Wrapper>
    </>
  );
}
